apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: pre-commit-manager
    title: pre-commit-manager
    description: Pre-Commit Manager installs Pre-Commit for you, a Git hooks configuration framework that helps you to push pre-validated code only.
    labels:
        pillar: platform
    annotations:
        github.com/project-slug: cat-home-experts/pre-commit-manager
        github.com/team-slug: cat-home-experts/engineering/platform/sre
        jira/project-key: PL
        backstage.io/techdocs-ref: dir:.
        backstage.io/linguist: 'https://github.com/cat-home-experts/pre-commit-manager'
spec:
    type: service
    owner: sre
    system: 
    lifecycle: production
